### PR TITLE
Update ks_porsche_962c_shorttail.ini

### PR DESCRIPTION
**Pull request by Ben-Cal**
wipers fixed!

### CODE REVIEW

**Comment by RustyChest** [comment]
Ben, please. You can amass your changes into one pull request rather than causing a bit of a mess.

**Comment by Ben-Cal** [comment]
> 
> 
> Ben, please. You can amass your changes into one pull request rather than causing a bit of a mess.

Hey and thank you for your help! I'm struggling a bit with github, I guess I'll have to delete the pull requests...I'll work it out, sorry for creating a mess!
Thank you! I'm struggling with how, I guess I'll have to delete

> 
> 
> Ben, please. You can amass your changes into one pull request rather than causing a bit of a mess.

Thank you and sorry, I can't work out how to

**Comment by RustyChest** [comment]
https://product.hubspot.com/blog/git-and-github-tutorial-for-beginners

**Review by EMT999 — COMMENTED** [review]
Yeah he ain't that bad tho ain't real he's kinda a saint

**Pull request closed without merging**
