### PR TITLE
Deutschlandring RainFX

### PR DESCRIPTION
**Pull request by Vannipo**

### CODE REVIEW

**Comment by Vannipo** [comment]
Alfie has no CSP RainFX, so he is not able to approve....

**Comment by Vannipo** [comment]
https://youtu.be/bB1AA7P_gYM

**Comment by RustyChest** [comment]
Since this is modded content that may be updated by the Author later down the line, I'd appreciate it if he gave you the go-ahead on at least the brighter lamp bulbs, as the Rain bit is understandable.

**Comment by Vannipo** [comment]
Removed lamp bulb stuff. I keep it just for me.
Now RainFX only.

**Pull request merged**
