### PR TITLE
Sterkfonteindam ext-config

### PR DESCRIPTION
**Pull request by victorcormier**
GrassFX config, new grass texture atlas, and better CSP lights for Votr's Sterkfonteindam Valley track.

### CODE REVIEW

**Comment by RustyChest** [comment]
Please re-package the grass.dds you're including here to be placed in extension\textures\grass_fx and be advised that x4 will have to be notified of this so he can include it in the next patch update as the textures folder isn't directly cloned upon each startup.

**Comment by Trava715** [comment]
> so he can include it in the next patch update

As far as I'm aware he removed all custom grass textures from common CSP directory breaking some tracks in the process a while back.

**Comment by victorcormier** [comment]
> Please re-package the grass.dds you're including here to be placed in extension\textures\grass_fx

> As far as I'm aware he removed all custom grass textures from common CSP directory breaking some tracks in the process a while back.

Hmm. So...

- Leave the custom grass DDS file as-is in the current directory? 
- Move to the proper directory as RustyChest requested, and adjust the path accordingly? 
- Or...custom grass textures aren't (currently?) supported at all through this repo?

Thanks for taking a look, in any case.

**Comment by Trava715** [comment]
As I said, as far as I'm aware the only grassfx textures placed in master/textures/grass_fx are the ones that Kunos content uses. Any custom ones should be placed within the track's extension folder.

**Comment by victorcormier** [comment]
I'll go ahead and just distribute the config and the texture together outside of the github repository, rather than risk having the config be auto-downloaded without the custom texture. Thanks again.

**Pull request closed without merging**
