### PR TITLE
Rain-FX Thomson Road

### PR DESCRIPTION
**Pull request by Vannipo**
Alfie has no CSP RainFX, so he is not able to approve....

### CODE REVIEW

**Comment by Vannipo** [comment]
All Alfie tracks have RainFX now, but this one won't get merged. Strange...

**Comment by Marocco2** [comment]
I really don't want an argument with Alfie, so it's way easier for me if you have his approval on this

**Comment by Marocco2** [comment]
Closed because Fat-Alfie has provided his rain config on newest update

**Pull request closed without merging**
