### PR TITLE
Update config ks_alfa_mito_qv.ini

### PR DESCRIPTION
**Pull request by modeewy25**
- Improved paint look, differentiating between solid and metallic colors.
- Fixed shaking exhaust (it missed the black interior part).
- Added exhaust smoke.
- Reduced tyre brightness.

### CODE REVIEW

**Comment by Marocco2** [comment]
May I see some screenshots of your work?

**Comment by modeewy25** [comment]
Screenshot_ks_alfa_mito_qv_magione_8-3-123-16-40-11
Screenshot_ks_alfa_mito_qv_magione_8-3-123-16-40-16
Screenshot_ks_alfa_mito_qv_magione_8-3-123-16-38-7
Screenshot_ks_alfa_mito_qv_magione_8-3-123-16-38-20
Screenshot_ks_alfa_mito_qv_magione_8-3-123-16-38-29
Screenshot_ks_alfa_mito_qv_magione_8-3-123-16-38-36
Screenshot_ks_alfa_mito_qv_magione_8-3-123-16-38-46
Screenshot_ks_alfa_mito_qv_magione_8-3-123-16-38-57
Screenshot_ks_alfa_mito_qv_magione_8-3-123-16-39-54
Screenshot_ks_alfa_mito_qv_magione_8-3-123-16-40-0
Screenshot_ks_alfa_mito_qv_magione_8-3-123-16-40-5

**Comment by modeewy25** [comment]
Just to clarify, my intention is to improve the look of the cars, and adding missing things, like shaking exhaust, wobbly wipers, etc. Still, i'm learning at the same time, so there could be mistakes in my config updates. 
PS: English it's not my native language, sorry for any mistake.

**Comment by modeewy25** [comment]
Regarding the screenshots, the black Alfa Romeo Mito QV (Nero) is an example of a solid color, while the blue one (Blu Tornado) is an example of a metallic color. I based this on an official Alfa Romeo brochure.
https://autocatalogarchive.com/wp-content/uploads/2018/03/Alfa-Romeo-MiTo-2011-UK.pdf

**Pull request merged**
