### PR TITLE
Update ks_ferrari_488_gt3.ini

### PR DESCRIPTION
**Pull request by CheesyManiac**
Completely overhauls the in-car screen to use a custom camera instead of the mirror texture. Fixes the exposure issue. Also adds new features and adds TC to the editable options.

### CODE REVIEW

**Comment by Marocco2** [comment]
Can you make a video showing the improvements with this new config?

**Comment by CheesyManiac** [comment]
Here you go:
https://youtu.be/7EcLbFigi0A

I don't feel like recording it in anything higher res.

**Comment by Marocco2** [comment]
> Here you go:
> https://youtu.be/7EcLbFigi0A
> 
> I don't feel like recording it in anything higher res.
> 
> Please test this as well. I did share it with some others before pushing here.

Seems good, good job!
Before I test this myself, do you know what is the minimum version of this config without breaking apart?

**Comment by CheesyManiac** [comment]
I used 1.80p141 to build it, but I tested it on 1.80p1 and it worked fine.

Versions 1.80p108 to 1.80p122 had issues with scriptable displays so it will probably not work on those versions. I included an error in script to warn people about that.

**Comment by Marocco2** [comment]
https://user-images.githubusercontent.com/3944248/217954340-ab12bd63-8abe-4484-93f4-876da6a4a390.mp4

Found this bug. Please fix before I could merge this

**Pull request merged**
